language: ruby

os:
  - linux
  - osx

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3

gemfile:
  - Gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/3.2.22.5.gemfile

before_script:
  - mysql -e 'create database the_role'
  - psql  -c 'create database the_role' -U postgres
  - cp config/database.yml.ci config/database.yml

script: "bundle exec rake db:bootstrap && bundle exec rspec --format documentation"
