language: ruby

os:
  - linux
  - osx

env:
  - TEST_ENV=3 DB=sqlite
  - TEST_ENV=3 DB=mysql
  - TEST_ENV=3 DB=postgresql
  - TEST_ENV=4 DB=sqlite
  - TEST_ENV=4 DB=mysql
  - TEST_ENV=4 DB=postgresql
  - TEST_ENV=4.1 DB=sqlite
  - TEST_ENV=4.1 DB=mysql
  - TEST_ENV=4.1 DB=postgresql
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3

gemfile:
  - Gemfile

before_script:
  - mysql -e 'create database the_role'
  - psql  -c 'create database the_role' -U postgres
  - cp config/database.yml.ci config/database.yml

script: "bundle install && bundle exec rake db:bootstrap && bundle exec rspec --format documentation"
