development:
  adapter: sqlite3
  database: db/the_role_dev.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/the_role_test.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/the_role_prod.db
  pool: 5
  timeout: 5000

# development:
#   adapter:  postgresql
#   database: the_role
#   username: postgres
#   password: qwerty

#   host:     localhost
#   encoding: unicode
#   reconnect: true
#   port: 5432
#   pool: 5
